name: ohbm
channels:
  - conda-forge
  - conda-forge/label/gcc7
dependencies:
  - numpy>=1.16.5
  - pandas
  - nibabel
  - nilearn>=0.7.1
  - sklearn-contrib-lightning
  - matplotlib==3.2.2
  - vtk
  - pip:
    - brainspace

